/**
 * Legacy lowercase / wrong-case URLs → canonical paths (exact match on pathname only).
 * Mirrors former next.config redirects that break on Windows when `source` matches
 * `destination` case-insensitively (e.g. /blog → /Blog re-triggers on /Blog → loop).
 *
 * Lookup key is pathname.toLowerCase(); redirect only when pathname !== destination.
 */
export const LEGACY_EXACT_REDIRECTS: Record<string, string> = {
  '/about': '/About',
  '/contact': '/Contact',
  '/faq': '/FAQ',
  '/cookies': '/Cookies',
  '/privacy': '/Privacy',
  '/terms': '/Terms',
  '/gdpr': '/GDPR',
  '/map': '/Map',
  '/wiki': '/Wiki',
  '/premium': '/Premium',
  '/join': '/Join',
  '/whatsapp': '/WhatsApp',
  '/pace': '/PACE',
  '/ico': '/ICO',
  '/blog': '/Blog',
  '/accessibility': '/Accessibility',
  '/complaints': '/Complaints',
  '/dataprotection': '/DataProtection',
  '/formslibrary': '/FormsLibrary',
  '/firms': '/Firms',
  '/forces': '/Forces',
  '/home': '/',
  '/f-a-q': '/FAQ',
  '/g-d-p-r': '/GDPR',
  '/termsandconditions': '/Terms',
  '/terms-and-conditions': '/Terms',
  '/howtobecome': '/HowToBecome',
  '/getwork': '/GetWork',
  '/findsupervisingsolicitor': '/FindSupervisingSolicitor',
  '/howtofindsupervisingsolicitor': '/FindSupervisingSolicitor',
  '/gofeatured': '/GoFeatured',
  '/escapefeecalculator': '/EscapeFeeCalculator',
  '/policestationrates': '/PoliceStationRates',
  '/policestationreppay': '/PoliceStationRepPay',
  '/policestationrepjobsuk': '/PoliceStationRepJobsUK',
  '/stationsdirectory': '/StationsDirectory',
  '/whatdoesrepdo': '/WhatDoesRepDo',
  '/dutysolicitorvsrep': '/DutySolicitorVsRep',
  '/beginnersguide': '/BeginnersGuide',
  '/commonoffencesguide': '/CommonOffencesGuide',
  '/interviewundercaution': '/InterviewUnderCaution',
  '/policedisclosureguide': '/PoliceDisclosureGuide',
  '/escapefeecalculator': '/EscapeFeeCalculator',
  '/policestationrates': '/PoliceStationRates',
  '/policestationreppay': '/PoliceStationRepPay',
  '/magistratescourtfees': '/MagistratesCourtFees',
  '/crowncourtfees': '/CrownCourtFees',
  '/gettingstarted': '/GettingStarted',
  '/resources': '/Resources',
  '/legalupdates': '/LegalUpdates',
  '/policestationrepsbycounty': '/PoliceStationRepsByCounty',
  '/solicitorpolicestationcoveruk': '/SolicitorPoliceStationCoverUK',
  '/buildportfolioguide': '/BuildPortfolioGuide',
  '/criminallawcareerguide': '/CriminalLawCareerGuide',
  '/prepareforcit': '/PrepareForCIT',
  '/aboutfounder': '/AboutFounder',
  '/kentpolicestationreps': '/KentPoliceStationReps',
  '/repfaqmaster': '/RepFAQMaster',
  '/subscribe': '/Subscribe',
  '/account': '/Account',
  '/profile': '/Profile',
  '/login': '/Account',
  '/sign-in': '/Account',
  '/rep/joanna-wayne': '/rep/joanne-wayne',
};
